# syntax=docker/dockerfile:experimental
# CUDA development image for building sources
FROM nvidia/cuda:12.1.1-devel-ubuntu20.04 as builder

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONDONTWRITEBYTECODE=1

# Install and update tools to minimize security vulnerabilities
RUN apt update -y && apt install -y software-properties-common wget apt-utils patchelf git libprotobuf-dev protobuf-compiler cmake \
    git bash curl python3 python3-pip \
    libtiff5-dev libjpeg8-dev libopenjp2-7-dev zlib1g-dev \
    libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python3-tk \
    libharfbuzz-dev libfribidi-dev libxcb1-dev
RUN unattended-upgrade
RUN apt-get autoremove -y && rm -rf /var/lib/apt/lists/*

RUN pip install -U pip wheel ipython setuptools==56.0.0 wheel cython
RUN pip install torch==2.1.0 --index-url https://download.pytorch.org/whl/cu121

WORKDIR /code
COPY . /code
RUN pip install -r requirements.txt
RUN MAX_JOBS=4 pip install flash-attn --no-build-isolation

CMD bash